server:
  port: 9092

spring:
  application:
    name: sen-events

  datasource:
    url: jdbc:postgresql://localhost:5433/sen_events_db
    username: postgres
    password: toor

  mail:
    host: smtp.gmail.com
    port: 587
    username: cheikhtall1199@gmail.com
    password: qcusmhmrqyicabzt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required : true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000

  jpa:
    hibernate:
      ddl-auto: update   # options : none | validate | update | create | create-drop | update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      fail-on-empty-beans: false

  security:
    jwt:
      secret: 7ad52f2cc1c5ef80e859728c099a69f28dfe1f2783f6afb737c6471849663eea9a982e153e458fbceaec15b28ab7b9c0bfadb037e3d0a3042333e9083e7a63cc1009f5f7df2bc3d788c427fe9613ccec902cf6cc0946101aac197a0167db461050cea32c260e7d9280efef2ee481e4c64b4c40927988d3d31c5dfe3d99196269f80f479552e8cb9c581a45827398b04cf0637e1a50ffe717c9d3322aeb32c3ff890bb0acc6a6c87e119ab32fc61d595bf1c6feb269a0e197e44b1670579bf7efc2c818a123e00c7b8a01064b959aeeb0d8c6b782456f1950402341d82edf5a4318e49fa8b9ef057a551bc52398292188deddb095f6f79f7cc87bf7ba4d86d98c
      expiration-ms: 86400000

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


